[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

  [[headers]]
for = "/api/*"
[headers.values]
Access-Control-Allow-Origin = "https://carbon-reduction-plan-ecosphere.netlify.app"
Access-Control-Allow-Credentials = "true"

